package generate;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName EXPORT_TASK
 */
@Data
public class ExportTask implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Long exportTaskId;

    /**
     * 导出类型：1-卖家导出自由资金明细
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String taskType;

    /**
     * 任务参数：json串
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String taskParams;

    /**
     * 卖家经营ID
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Long sBusiId;

    /**
     * 卖家用户ID
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Long sUserId;

    /**
     * 卖家公司名称英文
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String sComNameEn;

    /**
     * 卖家公司名称中文
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String sComNameCn;

    /**
     * 市场ID
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Long beneficiaryId;

    /**
     * 业务类型：1-WS、2-DS
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String businessType;

    /**
     * 起始日期，精确度yyyyMMdd
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date beginDate;

    /**
     * 截止日期，精确度yyyyMMdd
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date endDate;

    /**
     * 导出条数
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Long exportTotal;

    /**
     * 任务状态：0-待执行、1-执行中、2-执行成功、9-执行失败
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Short status;

    /**
     * 失败原因
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String failReason;

    /**
     * 重试次数
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Long retryNum;

    /**
     * 任务开始执行时间
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date executeTime;

    /**
     * 邮箱发送时间
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date sendEmailTime;

    /**
     * 添加人编号
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String adderNo;

    /**
     * 添加人姓名
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String adderName;

    /**
     * 添加时间
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date addTime;

    /**
     * 添加站点: TEL 电信、LOCAL 本地、PHX 凤凰、USA 美国
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String addSite;

    /**
     * 更新人编号
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String updaterNo;

    /**
     * 更新人姓名
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String updaterName;

    /**
     * 更新时间
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date updateTime;

    /**
     * 修改站点: TEL 电信、LOCAL 本地、PHX 凤凰、USA 美国
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String updateSite;

    /**
     * 操作人
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private String operatorIp;

    /**
     * REP_TIME
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private Date repTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EXPORT_TASK
     *
     * @mbg.generated Wed Jan 27 15:20:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
}